[colors.primary]
background = '#16130b'
foreground = '#eae1d4'
 
[colors.cursor]
text = '#eae1d4'
cursor = '#cfc5b4' 
 
[colors.selection]
text = '#16130b'
background = '#e5c36c'
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#e5c36c' 
yellow = '#755b0b' 
blue = '#e5c36c' 
magenta = '#aecfac' 
cyan = '#d6c5a0' 
white = '#BAC2DE' 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 

